### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Maxmudjon** [chaeplin/homebridge-mqttlock#1]
how to use.
Some payload not clear
how do I check through the MQTTlens ?

**Comment by chaeplin** [comment]
check https://github.com/nfarina/homebridge and homebridge-plugin.
my payload came from https://github.com/chaeplin/esp8266_and_arduino/blob/master/_49-emontxv2-esp-01-i2c/esp-01/esp-01.ino

**Comment by Maxmudjon** [comment]
thanks
